<<<<<<< HEAD
# Generated by Django 3.1.7 on 2021-04-17 01:27
=======
# Generated by Django 3.2 on 2021-04-16 00:15
>>>>>>> b3190ebba2ee8755b88a22fed1b070fded83a89d

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balconista',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Balconista')),
                ('rg', models.CharField(max_length=15, verbose_name='RG')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('data_nascimento', models.DateField(auto_now_add=True, verbose_name='Data da nascimento')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=12, verbose_name='Telefone')),
                ('cep', models.CharField(max_length=15, verbose_name='CEP')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail')),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('dt_nascimento', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
>>>>>>> b3190ebba2ee8755b88a22fed1b070fded83a89d
            ],
        ),
    ]
