# Generated by Django 3.1.7 on 2021-04-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_farmaceutico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balconista',
            name='telefone',
            field=models.IntegerField(verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='farmaceutico',
            name='telefone',
            field=models.CharField(max_length=12, verbose_name='Telefone'),
        ),
    ]
