# Generated by Django 3.1.7 on 2021-04-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20210417_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Balconista')),
                ('rg', models.CharField(max_length=15, verbose_name='RG')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('data_nascimento', models.DateField(auto_now_add=True, verbose_name='Data da nascimento')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=12, verbose_name='Telefone')),
                ('cep', models.CharField(max_length=15, verbose_name='CEP')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail')),
                ('foto', models.FileField(upload_to='foto de cadastro', verbose_name='Foto de cadastro do cliente')),
            ],
        ),
    ]
