# Generated by Django 3.2 on 2021-04-18 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_caixa'),
        ('principal', '0003_auto_20210417_2016'),
    ]

    operations = [
    ]
