# Generated by Django 3.2 on 2021-04-25 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20210425_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, default=0, verbose_name='Quantidade de Itens Comprados')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_compra', models.DateField(auto_now_add=True)),
                ('hora_compra', models.TimeField(auto_now_add=True)),
                ('data_hora_compra', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.fornecedor', verbose_name='Fornecedor')),
                ('produtos', models.ManyToManyField(to='principal.Produto')),
            ],
        ),
    ]
