# Generated by Django 3.2 on 2021-04-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contas_a_pagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('data_venc', models.DateField(blank=True, verbose_name='Data de vencimento')),
                ('valor_pagar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor a pagar')),
            ],
            options={
                'verbose_name': 'Contas a pagar',
                'verbose_name_plural': 'Contas a Pagar',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('comprovante', models.FileField(upload_to='foto da receita', verbose_name='Fazer upload do comprovante')),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('hora_pagamento', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
