# Generated by Django 3.2 on 2021-04-26 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_auto_20210425_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma_de_pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=14, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
            },
        ),
        migrations.AddField(
            model_name='venda',
            name='fm_pagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.forma_de_pagamento', verbose_name='Forma de Pagamento'),
        ),
    ]
